name: Print when successfully Pushed to main branch

on:
    push:
      branches: main
    pull_request:
      branches: main

jobs:
    print:
        runs-on: ubuntu-latest #It depends on the machine or cloud provider

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
      
            - name: Print Message
              run: |
                echo "Code has been pushed to the main branch Successfully"
                echo "We can do something here."
        